"""Sync the application version across every place it's referenced.

Single source of truth: ``bandcamp_auto_uploader/__version__.py``.

This script updates:
- ``config/pyproject.toml`` -> ``version = "X"``
- ``scripts/installer.iss`` -> ``#include "version.inc"`` (auto-generated)
- ``scripts/version.inc`` (generated, used by installer.iss)
- ``README.md`` -> the version badge image alt text

Usage:
    python scripts/set_version.py            # apply whatever is in __version__.py
    python scripts/set_version.py 4          # bump to 4 (and update __version__.py)
    python scripts/set_version.py 3b         # bump to 3b
    python scripts/set_version.py 4 --label "4 (stable)"  # set a custom label
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_PY = ROOT / "bandcamp_auto_uploader" / "__version__.py"
PYPROJECT = ROOT / "config" / "pyproject.toml"
INSTALLER_ISS = ROOT / "scripts" / "installer.iss"
VERSION_INC = ROOT / "scripts" / "version.inc"
README = ROOT / "README.md"

VERSION_PY_RE = re.compile(
    r'__version__\s*=\s*"(?P<version>[^"]+)"\s*\n'
    r'__version_label__\s*=\s*"(?P<label>[^"]+)"',
    re.MULTILINE,
)

PYPROJECT_VERSION_RE = re.compile(r'^version\s*=\s*"[^"]+"\s*$', re.MULTILINE)

INSTALLER_DIRECT_VERSION_RE = re.compile(
    r'#define\s+MyAppVersion\s+"[^"]+"',
)

INSTALLER_INCLUDE_RE = re.compile(
    r'#include\s+"version\.inc"',
)

README_BADGE_RE = re.compile(
    r'(img\.shields\.io/badge/Version-)([^"-]+)(-blue)',
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync the Bandcamp Auto Uploader version.")
    parser.add_argument(
        "version",
        nargs="?",
        help="New version token (e.g. 4, 3b, 4rc1). Defaults to whatever is in __version__.py.",
    )
    parser.add_argument(
        "--label",
        help="Optional override for the human-readable version label.",
    )
    return parser.parse_args()


def read_current_versions() -> tuple[str, str]:
    text = VERSION_PY.read_text(encoding="utf-8")
    match = VERSION_PY_RE.search(text)
    if not match:
        raise RuntimeError(
            f"Could not find __version__/__version_label__ in {VERSION_PY}"
        )
    return match.group("version"), match.group("label")


def write_version_py(version: str, label: str) -> None:
    text = VERSION_PY.read_text(encoding="utf-8")
    new_text, count = VERSION_PY_RE.subn(
        f'__version__ = "{version}"\n__version_label__ = "{label}"',
        text,
        count=1,
    )
    if count == 0:
        raise RuntimeError(f"Failed to update {VERSION_PY}")
    VERSION_PY.write_text(new_text, encoding="utf-8")


def update_pyproject(version: str) -> None:
    text = PYPROJECT.read_text(encoding="utf-8")
    new_text, count = PYPROJECT_VERSION_RE.subn(f'version = "{version}"', text, count=1)
    if count == 0:
        raise RuntimeError(f"Could not find 'version = ...' in {PYPROJECT}")
    PYPROJECT.write_text(new_text, encoding="utf-8")


def write_version_inc(version: str, label: str) -> None:
    VERSION_INC.write_text(
        "; Auto-generated by scripts/set_version.py -- do not edit by hand.\n"
        f'#define MyAppVersion "{version}"\n'
        f'#define MyAppVersionLabel "{label}"\n',
        encoding="utf-8",
    )


def update_installer_iss() -> None:
    text = INSTALLER_ISS.read_text(encoding="utf-8")

    if INSTALLER_DIRECT_VERSION_RE.search(text):
        text, _ = INSTALLER_DIRECT_VERSION_RE.subn(
            '#define MyAppVersion "{#MyAppVersion}"',
            text,
            count=1,
        )

    if not INSTALLER_INCLUDE_RE.search(text):
        insert_at = text.find("[Setup]")
        if insert_at == -1:
            raise RuntimeError(f"Could not find [Setup] section in {INSTALLER_ISS}")
        text = (
            text[:insert_at]
            + '#include "version.inc"\n\n'
            + text[insert_at:]
        )

    INSTALLER_ISS.write_text(text, encoding="utf-8")


def update_readme(version: str) -> None:
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    new_text, count = README_BADGE_RE.subn(
        rf'\g<1>{version}\g<3>',
        text,
        count=1,
    )
    if count == 0:
        print(f"  (no version badge found in {README}, skipping)")
        return
    README.write_text(new_text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    current_version, current_label = read_current_versions()
    new_version = args.version or current_version
    new_label = args.label or (current_label if args.version is None else _default_label(new_version))

    if not re.match(r"^\d+(?:\.\d+)*(?:(?:[ab]|rc)\d*)?$", new_version):
        print(f"Refusing to set version {new_version!r} (does not look like a version token).")
        return 1

    print(f"Setting version to {new_version!r} (label: {new_label!r})")
    write_version_py(new_version, new_label)
    update_pyproject(new_version)
    write_version_inc(new_version, new_label)
    update_installer_iss()
    update_readme(new_version)
    print("Done. Updated files:")
    print(f"  - {VERSION_PY.relative_to(ROOT)}")
    print(f"  - {PYPROJECT.relative_to(ROOT)}")
    print(f"  - {VERSION_INC.relative_to(ROOT)}  (generated)")
    print(f"  - {INSTALLER_ISS.relative_to(ROOT)}")
    print(f"  - {README.relative_to(ROOT)}")
    return 0


def _default_label(version: str) -> str:
    suffix = version.lstrip("0123456789.")
    if suffix.startswith("b"):
        return f"{version} (beta)"
    if suffix.startswith("a"):
        return f"{version} (alpha)"
    if suffix.startswith("rc"):
        return f"{version} (release candidate)"
    return version


if __name__ == "__main__":
    sys.exit(main())
